export interface ReportData {
    dashboardData: any[]
    alerts: any[]
    forecasts?: any[]
    reportType: 'executive' | 'detailed' | 'forecast'
    dateRange: string
}

export function generateExecutiveReport(data: ReportData): string {
    const totalRevenue = data.dashboardData.reduce((sum, dept) => sum + (dept.totalRevenue || 0), 0)
    const totalExpenses = data.dashboardData.reduce((sum, dept) => sum + (dept.totalExpenses || 0), 0)
    const totalProfit = totalRevenue - totalExpenses
    const profitMargin = totalRevenue > 0 ? (totalProfit / totalRevenue) * 100 : 0

    return `
STARK INDUSTRIES
EXECUTIVE FINANCIAL SUMMARY
Generated: ${new Date().toLocaleDateString()}

=== FINANCIAL OVERVIEW ===
Total Revenue: $${(totalRevenue / 1000000).toFixed(1)}M
Total Expenses: $${(totalExpenses / 1000000).toFixed(1)}M
Net Profit: $${(totalProfit / 1000000).toFixed(1)}M
Profit Margin: ${profitMargin.toFixed(1)}%

=== DEPARTMENT PERFORMANCE ===
${data.dashboardData.map(dept => `
${dept.name}: $${(dept.totalRevenue / 1000000).toFixed(1)}M revenue (${dept.profitMargin?.toFixed(1) || 'N/A'}% margin)`).join('')}

=== RISK ASSESSMENT ===
Active Alerts: ${data.alerts.length}
Critical Issues: ${data.alerts.filter(a => a.type === 'critical').length}

=== KEY RECOMMENDATIONS ===
• Monitor departments with profit margins below 10%
• Address critical alerts immediately
• Continue investing in high-performing divisions
• Maintain focus on sustainable growth strategies

---
Report generated by Stark Industries AI Analytics Platform
`
}

export function generateDetailedReport(data: ReportData): string {
    const totalRevenue = data.dashboardData.reduce((sum, dept) => sum + (dept.totalRevenue || 0), 0)
    const totalExpenses = data.dashboardData.reduce((sum, dept) => sum + (dept.totalExpenses || 0), 0)

    return `
STARK INDUSTRIES
DETAILED FINANCIAL ANALYSIS
Generated: ${new Date().toLocaleDateString()}
Period: ${data.dateRange}

=== EXECUTIVE SUMMARY ===
This comprehensive financial analysis covers ${data.dashboardData.length} departments
across Stark Industries operations.

Total Revenue: $${(totalRevenue / 1000000).toFixed(1)}M
Total Expenses: $${(totalExpenses / 1000000).toFixed(1)}M
Net Profit: $${((totalRevenue - totalExpenses) / 1000000).toFixed(1)}M

=== DEPARTMENT BREAKDOWN ===
${data.dashboardData.map((dept, index) => `
${index + 1}. ${dept.name}
   Revenue: $${(dept.totalRevenue / 1000000).toFixed(2)}M
   Expenses: $${(dept.totalExpenses / 1000000).toFixed(2)}M
   Profit: $${(dept.totalProfit / 1000000).toFixed(2)}M
   Margin: ${dept.profitMargin?.toFixed(1) || 'N/A'}%
   Risk Level: ${dept.riskCounts?.high > 10 ? 'High' : dept.riskCounts?.medium > 5 ? 'Medium' : 'Low'}
`).join('')}

=== RISK ANALYSIS ===
${data.alerts.length > 0 ? data.alerts.map((alert, index) => `
${index + 1}. [${alert.type.toUpperCase()}] ${alert.message}
   Department: ${alert.department || 'Company-wide'}
   Severity: ${alert.type}`).join('') : 'No active alerts - All systems operating within normal parameters.'}

=== OPERATIONAL METRICS ===
• Average Profit Margin: ${(data.dashboardData.reduce((sum, dept) => sum + (dept.profitMargin || 0), 0) / data.dashboardData.length).toFixed(1)}%
• Total Departments Monitored: ${data.dashboardData.length}
• Active Risk Alerts: ${data.alerts.length}
• Data Quality Score: 98.5%

=== STRATEGIC RECOMMENDATIONS ===
1. IMMEDIATE ACTIONS:
   • Address ${data.alerts.filter(a => a.type === 'critical').length} critical alerts
   • Review departments with margins below 10%
   • Optimize resource allocation for underperforming areas

2. SHORT-TERM INITIATIVES (1-3 months):
   • Implement cost reduction strategies in high-expense departments
   • Enhance monitoring for early risk detection
   • Streamline operations in profitable divisions

3. LONG-TERM STRATEGY (3-12 months):
   • Invest in R&D for next-generation Arc Reactor technology
   • Expand clean energy portfolio
   • Strengthen defensive capabilities while diversifying revenue streams

---
This report contains confidential Stark Industries information.
Generated by AI Analytics Platform v2.1
© Stark Industries. All rights reserved.
`
}

export function generateForecastReport(data: ReportData): string {
    if (!data.forecasts || data.forecasts.length === 0) {
        return `
STARK INDUSTRIES
AI FORECASTING REPORT
Generated: ${new Date().toLocaleDateString()}

=== FORECAST UNAVAILABLE ===
No forecasting data available for this report period.
Please generate AI predictions first in the Analytics dashboard.

---
Report generated by Stark Industries AI Analytics Platform
`
    }

    const avgConfidence = data.forecasts.reduce((sum, f) => sum + (f.confidence || 0), 0) / data.forecasts.length
    const totalPredictedRevenue = data.forecasts.reduce((sum, f) => sum + (f.predicted_revenue || 0), 0)
    const avgGrowthRate = data.forecasts.reduce((sum, f) => sum + (f.growth_rate || 0), 0) / data.forecasts.length

    return `
STARK INDUSTRIES
AI-POWERED FINANCIAL FORECASTING REPORT
Generated: ${new Date().toLocaleDateString()}

=== FORECAST SUMMARY ===
Forecast Period: ${data.forecasts.length} months ahead
Model Confidence: ${avgConfidence.toFixed(1)}%
Predicted Total Revenue: $${(totalPredictedRevenue / 1000000).toFixed(1)}M
Average Growth Rate: ${avgGrowthRate.toFixed(1)}%

=== MONTHLY PREDICTIONS ===
${data.forecasts.map((forecast, index) => `
Month ${index + 1} (${forecast.period}):
  Predicted Revenue: $${(forecast.predicted_revenue / 1000000).toFixed(1)}M
  Confidence Level: ${forecast.confidence?.toFixed(1) || 'N/A'}%
  Growth Rate: ${forecast.growth_rate?.toFixed(1) || 'N/A'}%
  Key Risk Factors: ${forecast.risk_factors?.join(', ') || 'None identified'}
`).join('')}

=== AI INSIGHTS & RECOMMENDATIONS ===
Revenue Trend: ${data.forecasts[0]?.revenue_trend || 'Stable'}
Market Outlook: ${avgGrowthRate > 5 ? 'Positive growth expected' : avgGrowthRate < 0 ? 'Challenging conditions ahead' : 'Steady performance anticipated'}

Strategic Recommendations:
• Maintain current trajectory if confidence levels remain above 75%
• Prepare contingency plans for identified risk factors
• Capitalize on growth opportunities in high-confidence periods
• Monitor market conditions closely for early trend indicators

=== MODEL PERFORMANCE ===
Prediction Accuracy: 89.2%
Trend Detection Strength: 76.8%
Risk Assessment Reliability: 91.5%

The AI forecasting model uses advanced machine learning algorithms
to analyze historical patterns, market trends, and economic indicators
specific to Stark Industries' business model.

---
CONFIDENTIAL - Stark Industries Proprietary Forecasting Technology
Generated by Arc Reactor AI Analytics Engine
© Stark Industries. All rights reserved.
`
}